services:
  setak:
    container_name: my-setak-app
    build:
      context: .
      dockerfile: Dockerfile
    image: alirezafazli29/setak:dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8000:8080"
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    